CREATE TABLE NAVE(
	ID_NAVE SERIAL PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(150) NOT NULL,
	PAIS VARCHAR(255)NOT NULL,
	POTENCIA INT NOT NULL,
	ALTURA INT NOT NULL,
	PESO INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	
	CONSTRAINT FK_NAVE_ID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_NAVE(ID_CATEGORIA)
);